{% set name = "solidspy" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/kssgarcia/SolidsPy.git
  git_tag: v{{ version }}

build:
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - easygui
    - meshio >=5.0

test:
  imports:
    - solidspy

about:
  home: "https://github.com/yourusername/SolidsPyKevin"
  license: "MIT"
  license_file: "LICENSE"
  summary: "A Python package for finite element analysis."
  description: |
    SolidsPyKevin is a Python library for performing finite element analysis.
  doc_url: "https://github.com/yourusername/SolidsPyKevin#readme"
  dev_url: "https://github.com/yourusername/SolidsPyKevin"

extra:
  recipe-maintainers:
    - kssgarcia

channels:
  - conda-forge